
const BASE_HORIZONTAL_MARGIN = 24.0;

const BODY2_TEXT_FONT_SIZE = 18.0;
const TITLE_TEXT_FONT_SIZE = 24.0;
const BODY1_TEXT_FONT_SIZE = 16.0;
const CAPTION_TEXT_FONT_SIZE = 14.0;
const CAPTION_SMALLER_TEXT_FONT_SIZE = 12.0;

const CATEGORY_INITIAL_TEXT_FONT_SIZE = 20.0;

const SUBMIT_BUTTON_HEIGHT = 48.0;

const COMMON_DIVIDER_THICKNESS = 0.8;

const COMMON_BORDER_RADIUS = 6.0;

const LARGER_DIVIDER_THICKNESS = 8.0;